/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ClientController;
import domain.Analiza;
import domain.KartonPacijenta;
import domain.Lekar;
import domain.Uput;
import domain.VrstaUzorka;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maja
 */
public class FrmKreiranjeUputa extends javax.swing.JDialog {

    Lekar lekar;
    KartonPacijenta pacijent;
    /**
     * Creates new form FrmKreiranjeUputa
     */
    public FrmKreiranjeUputa(java.awt.Frame parent, boolean modal, KartonPacijenta pacijent, Lekar l) {
        super(parent, modal);
        initComponents();
        this.pacijent=pacijent;
        prepareForm(pacijent.getJmbg());
        lekar = l;
        ClientController.getInstance().setFrmUput(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDijagnoza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSifraUputa = new javax.swing.JTextField();
        btnKreirajUput = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbVrstaUzorka = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbAnaliza = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kreiranje uputa za laboratorijske analize"));

        jLabel1.setText("JMBG pacijenta:");

        txtJMBG.setEnabled(false);

        jLabel2.setText("Datum:");

        txtDatum.setEnabled(false);

        jLabel3.setText("Uputna dijagnoza:");

        jLabel6.setText("Sifra uputa:");

        txtSifraUputa.setEnabled(false);

        btnKreirajUput.setText("Kreiraj uput");
        btnKreirajUput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajUputActionPerformed(evt);
            }
        });

        jLabel5.setText("Vrsta uzorka:");

        cbVrstaUzorka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Analiza:");

        cbAnaliza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(txtSifraUputa)
                                .addGap(170, 170, 170))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDijagnoza)
                                    .addComponent(cbVrstaUzorka, 0, 323, Short.MAX_VALUE)
                                    .addComponent(cbAnaliza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnKreirajUput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSifraUputa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVrstaUzorka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbAnaliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnKreirajUput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajUputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajUputActionPerformed
        try {
            Uput u = new Uput();
            u.setPacijent(pacijent);
            u.setAnaliza(cbAnaliza.getSelectedItem().toString());
            u.setVrstaUzorka(cbVrstaUzorka.getSelectedItem().toString());
            u.setLekar(lekar);
            u.setDatumUputa(new Date());
            u.setUputnaDijagnoza(txtDijagnoza.getText());
            ClientController.getInstance().insertUput(u);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnKreirajUputActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajUput;
    private javax.swing.JComboBox<String> cbAnaliza;
    private javax.swing.JComboBox<String> cbVrstaUzorka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDijagnoza;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtSifraUputa;
    // End of variables declaration//GEN-END:variables

    private void prepareForm(Long jmbg) {
        txtJMBG.setText(jmbg.toString());
        Date date = new Date();
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        txtDatum.setText(formatter.format(date));
        
        Analiza analize = new Analiza();
        cbAnaliza.setModel(new DefaultComboBoxModel(analize.getAnalize().toArray()));
        
        VrstaUzorka uzorci = new VrstaUzorka();
        cbVrstaUzorka.setModel(new DefaultComboBoxModel(uzorci.getUzorci().toArray()));
    }
    
    public void notifyInsert(String message, Uput u) {
        JOptionPane.showMessageDialog(this, message);
        if(u!=null) 
           txtSifraUputa.setText(u.getSifraUputa().toString());
    }
}
