/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ClientController;
import domain.Analiza;
import domain.VrsteAnaliza;
import domain.KartonPacijenta;
import domain.Lekar;
import domain.Uput;
import domain.VrstaUzorka;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import javax.swing.text.TableView.TableRow;

/**
 *
 * @author Maja
 */
public class FrmKreiranjeUputa extends javax.swing.JDialog {
    
    Lekar lekar;
    KartonPacijenta pacijent;
    DefaultTableModel tblModel;
    List<Analiza> analize;

    /**
     * Creates new form FrmKreiranjeUputa
     */
    public FrmKreiranjeUputa(java.awt.Frame parent, boolean modal, KartonPacijenta pacijent, Lekar l) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.pacijent = pacijent;
        prepareForm(pacijent.getJmbg());
        lekar = l;
        analize = new ArrayList<>();
        ClientController.getInstance().setFrmUput(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDijagnoza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSifraUputa = new javax.swing.JTextField();
        btnKreirajUput = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalize = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbUzorci = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbAnalize = new javax.swing.JComboBox<>();
        btnDodajAnalizu = new javax.swing.JButton();
        btnObrisiAnalizu = new javax.swing.JButton();
        btnOsvezi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kreiranje uputa za laboratorijske analize"));

        jLabel1.setText("JMBG pacijenta:");

        txtJMBG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtJMBG.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtJMBG.setEnabled(false);

        jLabel2.setText("Datum:");

        txtDatum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDatum.setEnabled(false);

        jLabel3.setText("Uputna dijagnoza:");

        jLabel6.setText("Sifra uputa:");

        txtSifraUputa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSifraUputa.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtSifraUputa.setEnabled(false);

        btnKreirajUput.setText("Kreiraj uput");
        btnKreirajUput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajUputActionPerformed(evt);
            }
        });

        tblAnalize.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblAnalize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vrsta uzorka", "Analiza"
            }
        ));
        jScrollPane1.setViewportView(tblAnalize);

        jLabel4.setText("Vrsta uzorka:");

        cbUzorci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Vrsta analize:");

        cbAnalize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodajAnalizu.setText("Dodaj analizu");
        btnDodajAnalizu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAnalizuActionPerformed(evt);
            }
        });

        btnObrisiAnalizu.setText("Obrisi analizu");
        btnObrisiAnalizu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiAnalizuActionPerformed(evt);
            }
        });

        btnOsvezi.setText("Osvezi");
        btnOsvezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219)
                        .addComponent(btnKreirajUput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatum))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(txtSifraUputa)
                                .addGap(170, 170, 170))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(txtDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(cbUzorci, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(btnDodajAnalizu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnObrisiAnalizu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAnalize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSifraUputa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbUzorci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbAnalize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajAnalizu)
                    .addComponent(btnObrisiAnalizu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajUput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajUputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajUputActionPerformed
        try {
            Uput u = new Uput();
            u.setPacijent(pacijent);
            u.setAnalize(analize);
            u.setLekar(lekar);
            u.setDatumUputa(new Date());
            u.setUputnaDijagnoza(txtDijagnoza.getText());
            ClientController.getInstance().insertUput(u);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnKreirajUputActionPerformed

    private void btnDodajAnalizuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAnalizuActionPerformed
        Analiza a = new Analiza();
        a.setVrstaAnalize(cbAnalize.getSelectedItem().toString());
        a.setVrstaUzorka(cbUzorci.getSelectedItem().toString());
        analize.add(a);
        
        Object[] row = {cbUzorci.getSelectedItem().toString(), cbAnalize.getSelectedItem().toString()};
        tblModel.addRow(row);
    }//GEN-LAST:event_btnDodajAnalizuActionPerformed

    private void btnObrisiAnalizuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiAnalizuActionPerformed
        int row = tblAnalize.getSelectedRow();
        if (row != -1) {
            analize.remove(row);
            tblModel.removeRow(row);
        }
        System.out.println("Ispis analiza:");
        for (Analiza a : analize) {
            System.out.println(a);
        }
    }//GEN-LAST:event_btnObrisiAnalizuActionPerformed

    private void btnOsveziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziActionPerformed
        txtSifraUputa.setText("");
        tblModel.setRowCount(0);
        txtSifraUputa.setText("");
        analize.removeAll(analize);
        txtDijagnoza.setText("");
    }//GEN-LAST:event_btnOsveziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAnalizu;
    private javax.swing.JButton btnKreirajUput;
    private javax.swing.JButton btnObrisiAnalizu;
    private javax.swing.JButton btnOsvezi;
    private javax.swing.JComboBox<String> cbAnalize;
    private javax.swing.JComboBox<String> cbUzorci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnalize;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDijagnoza;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtSifraUputa;
    // End of variables declaration//GEN-END:variables

    private void prepareForm(String jmbg) {
        txtJMBG.setText(jmbg);
        Date date = new Date();
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        txtDatum.setText(formatter.format(date));
        
        cbAnalize.setModel(new DefaultComboBoxModel(new VrsteAnaliza().getAnalize().toArray()));
        cbUzorci.setModel(new DefaultComboBoxModel(new VrstaUzorka().getUzorci().toArray()));
        
        tblModel = (DefaultTableModel) tblAnalize.getModel();
        tblModel.setRowCount(0);
        
    }
    
    public void notifyInsert(String message, Uput u) {
        JOptionPane.showMessageDialog(this, message);
        if (u != null) {
            try {
                txtSifraUputa.setText(u.getSifraUputa().toString());
                ClientController.getInstance().notifyOthers();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
}
