/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import communication.Response;
import communication.ResponseType;
import component.TableModelAnalize;
import component.TableModelUputi;
import controller.ClientController;
import domain.Analiza;
import domain.KartonPacijenta;
import domain.KrvnaGrupa;
import domain.Lekar;
import domain.Rezultat;
import domain.Uput;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Maja
 */
public class FrmMain_Lekar extends javax.swing.JFrame {

    private Lekar lekar;
    KartonPacijenta trenutni_pacijent;
    TableModelUputi tblModelUputi = new TableModelUputi();
    TableModelAnalize tblModelAnalize = new TableModelAnalize();
    List<Uput> uputi;
    List<Analiza> analize;
    List<Rezultat> rezultati;

    /**
     * Creates new form FrmMain_Lekar
     */
    public FrmMain_Lekar(Lekar lekar) {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.lekar = lekar;
        prepareForm();
        ClientController.getInstance().setFrmLekar(this);
        uputi = new ArrayList<>();
        analize = new ArrayList<>();
        rezultati = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblTrenutniLekar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtJMBGnadji = new javax.swing.JTextField();
        btnNadji = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnOcisti = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtJMBG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLBO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbPol = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        datumRodjenja = new org.jdatepicker.JDatePicker();
        jLabel10 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKontakt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbKrvnaGrupa = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHronicneDijagnoze = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtLekar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalize = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblUputi = new javax.swing.JTable();
        btnNoviKarton = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNoviUput = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MedicalIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel2.setVerifyInputWhenFocusTarget(false);

        lblTrenutniLekar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTrenutniLekar.setText("Ime lekara");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Pretrazi karton pacijenta");

        txtJMBGnadji.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtJMBGnadji.setText("1111111111111");

        btnNadji.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNadji.setText("Nadji");
        btnNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadjiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("JMBG");

        btnOcisti.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnOcisti.setText("Ocisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTrenutniLekar)
                .addGap(198, 198, 198))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtJMBGnadji, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(btnNadji, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTrenutniLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJMBGnadji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnNadji, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 466;
        gridBagConstraints.ipady = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 80, 0, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Podaci o pacijentu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18), new java.awt.Color(102, 204, 255))); // NOI18N

        txtJMBG.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("JMBG");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("LBO");

        txtLBO.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Ime");

        txtIme.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setText("Prezime");

        txtPrezime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Pol");

        cbPol.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbPol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Datum rodjenja");

        datumRodjenja.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Adresa");

        txtAdresa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Kontakt telefon");

        txtKontakt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPol, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(datumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtLBO, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel15)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLBO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel15)
                .addGap(28, 28, 28)
                .addComponent(cbPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(11, 11, 11)
                .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel1.add(jPanel3);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Krvna grupa");

        cbKrvnaGrupa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbKrvnaGrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Hronicne dijagnoze");

        txtHronicneDijagnoze.setColumns(20);
        txtHronicneDijagnoze.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtHronicneDijagnoze.setRows(5);
        jScrollPane2.setViewportView(txtHronicneDijagnoze);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Izabrani lekar");

        txtLekar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtLekar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLekar.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(cbKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(cbKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(txtLekar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("Lista uputa");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Analize i rezultati");

        tblAnalize.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblAnalize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnalizeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnalize);

        tblUputi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblUputi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUputi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUputiMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblUputi);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel14)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel5);

        btnNoviKarton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNoviKarton.setText("Kreiraj karton novog pacijenta");
        btnNoviKarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviKartonActionPerformed(evt);
            }
        });
        jPanel1.add(btnNoviKarton);

        btnUpdate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnUpdate.setText("Zameni");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnNoviUput.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNoviUput.setText("Kreiraj novi uput");
        btnNoviUput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviUputActionPerformed(evt);
            }
        });
        jPanel1.add(btnNoviUput);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.ipady = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 80, 0, 88);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoviUputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviUputActionPerformed
        Long jmbg;
        try {
            jmbg = Long.valueOf(txtJMBG.getText());
            new FrmKreiranjeUputa(this, true, trenutni_pacijent, lekar).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Morate prvo odabrati pacijenta za kojeg kreirate uput");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnNoviUputActionPerformed

    private void btnNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadjiActionPerformed
        nadji();
    }//GEN-LAST:event_btnNadjiActionPerformed

    private void tblUputiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUputiMouseClicked

        int row = tblUputi.rowAtPoint(evt.getPoint());

        Uput u = tblModelUputi.getUput(row);
        analize = u.getAnalize();

        try {
            ClientController.getInstance().getRezultatiAnaliza(analize);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain_Lekar.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_tblUputiMouseClicked

    private void btnNoviKartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviKartonActionPerformed
        try {

            validateForm();
            KartonPacijenta k = getPacijentData();
            ClientController.getInstance().insertNoviKarton(k);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ovde je greska " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnNoviKartonActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            validateForm();
            KartonPacijenta k = getPacijentData();
            ClientController.getInstance().updatePacijent(k);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed

        ocisti();

    }//GEN-LAST:event_btnOcistiActionPerformed

    private void tblAnalizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnalizeMouseClicked
        int row = tblAnalize.rowAtPoint(evt.getPoint());

        JOptionPane.showMessageDialog(this, tblModelAnalize.showAnalizaRezultat(row));

    }//GEN-LAST:event_tblAnalizeMouseClicked

    private void prepareForm() {
        List<String> pol = new ArrayList<>();
        pol.add("Muski");
        pol.add("Zenski");
        pol.add("Nije odredjeno");

        cbPol.setModel(new DefaultComboBoxModel(pol.toArray()));

        tblUputi.setModel(tblModelUputi);
        tblAnalize.setModel(tblModelAnalize);

        KrvnaGrupa kg = new KrvnaGrupa();

        cbKrvnaGrupa.setModel(new DefaultComboBoxModel(kg.getKrvneGrupe().toArray()));

        lblTrenutniLekar.setText(lekar.getIme() + " " + lekar.getPrezime() + " (" + lekar.getUsername() + ")");

    }

    public void showKartonPacijenta(Response response) {
        if (response.getResponseType().equals(ResponseType.SUCCESS)) {
            KartonPacijenta pacijent = (KartonPacijenta) response.getResponse();
            trenutni_pacijent = pacijent;
            txtJMBG.setText(pacijent.getJmbg());
            if (pacijent.getLbo() != null) {
                txtLBO.setText(pacijent.getLbo());
            }
            txtAdresa.setText(pacijent.getAdresa());
            txtIme.setText(pacijent.getIme());
            txtPrezime.setText(pacijent.getPrezime());
            cbKrvnaGrupa.setSelectedItem(pacijent.getKrvnaGrupa());
            txtKontakt.setText(pacijent.getKontaktTelefon());
            cbPol.setSelectedItem(pacijent.getPol().toString());
            txtHronicneDijagnoze.setText(pacijent.getHronicneDijagnoze());

            uputi = pacijent.getUputi();
            System.out.println("Stigne li kod do ovde uopste");
            for (Uput u : uputi) {
                System.out.println(u);
            }

            tblModelUputi.setUputi(uputi);

            txtLekar.setText(pacijent.getLekar().getIme() + " " + pacijent.getLekar().getPrezime());

            Date datumR = pacijent.getDatumRodjenja();
            System.out.println(datumR.toString());
            String datum[] = datumR.toString().split("-");
            int godina = Integer.valueOf(datum[0]);
            int mesec = Integer.valueOf(datum[1]) - 1;
            int dan = Integer.valueOf(datum[2]);
            datumRodjenja.getModel().setDate(godina, mesec, dan);
            datumRodjenja.getModel().setSelected(true);

        }
        else JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje karton pacijenta.");
    }

    public void showRezultati(Response response) {
        if (response.getResponseType().equals(ResponseType.SUCCESS)) {
            rezultati = (List<Rezultat>) response.getResponse();

            System.out.println("Rezultati: ");
            for (Rezultat r : rezultati) {
                System.out.println(r);
            }

            tblModelAnalize.setAnalizeRezultati(analize, rezultati);
        }

    }

    private void validateForm() throws Exception {
        String error = "";
        if (txtJMBG.getText().trim().isEmpty()) {
            error += "Niste upisali JMBG!\n";
        } else {
            try {
                Long jmbg = Long.valueOf(txtJMBG.getText());
            } catch (Exception e) {
                error += "Neispravan format JMBG-a!\n";
            }
        }
        if (!txtLBO.getText().equals("")) {
            try {
                Long lbo = Long.valueOf(txtLBO.getText());
            } catch (Exception e) {
                error += "Neispravan format LBO-a!\n";
            }
        }
        if (!error.isEmpty()) {
            throw new Exception(error);
        }
    }

    private KartonPacijenta getPacijentData() throws Exception {
        KartonPacijenta k = new KartonPacijenta();
        k.setJmbg(txtJMBG.getText().trim());

        k.setLbo(txtLBO.getText().trim());
        k.setAdresa(txtAdresa.getText());
        k.setIme(txtIme.getText());
        k.setPrezime(txtPrezime.getText());
        k.setKrvnaGrupa(cbKrvnaGrupa.getSelectedItem().toString());
        k.setKontaktTelefon(txtKontakt.getText());
        k.setPol(cbPol.getSelectedItem().toString());
        k.setHronicneDijagnoze(txtHronicneDijagnoze.getText());
        k.setLekar(lekar);

        int dan = datumRodjenja.getModel().getDay();
        int mesec = datumRodjenja.getModel().getMonth();
        int god = datumRodjenja.getModel().getYear();

        Date date = new Date(god - 1900, mesec, dan);

        k.setDatumRodjenja(date);

        return k;

    }

    public void notifyUser(String message) {
        JOptionPane.showMessageDialog(this, message);
        try {
            ClientController.getInstance().notifyOthers();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain_Lekar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void refresh() {
        // nadji();
    }

    private void nadji() {

        ocisti();
        String strJmbg = txtJMBGnadji.getText();

        if (!strJmbg.isEmpty()) {
            try {

                ClientController.getInstance().getKartonPacijenta(strJmbg, lekar.getUsername());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neodgovarajuca vrednost JMBG-a!");
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate uneti kriterijum za pretragu!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNadji;
    private javax.swing.JButton btnNoviKarton;
    private javax.swing.JButton btnNoviUput;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbKrvnaGrupa;
    private javax.swing.JComboBox<String> cbPol;
    private org.jdatepicker.JDatePicker datumRodjenja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTrenutniLekar;
    private javax.swing.JTable tblAnalize;
    private javax.swing.JTable tblUputi;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextArea txtHronicneDijagnoze;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtJMBGnadji;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtLBO;
    private javax.swing.JTextField txtLekar;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    private void ocisti() {
        if (rezultati != null) {
            rezultati.removeAll(rezultati);
        }
        if (uputi != null) {
            uputi.removeAll(uputi);
        }
        if (analize != null) {
            analize.removeAll(analize);
        }

        tblModelUputi.setUputi(uputi);
        tblModelAnalize.setAnalizeRezultati(analize, rezultati);

        txtJMBG.setText("");
        txtHronicneDijagnoze.setText("");
        txtAdresa.setText("");
        txtLBO.setText("");
        txtIme.setText("");
        txtPrezime.setText("");
        cbKrvnaGrupa.setSelectedItem("A+");
        txtKontakt.setText("");
        cbPol.setSelectedItem("Muski");
        txtLekar.setText("");
    }

}
