/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import communication.Response;
import communication.ResponseType;
import component.TableModelAnalize;
import controller.ClientController;
import domain.Analiza;
import domain.Laborant;
import domain.Rezultat;
import domain.Uput;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maja
 */
public class FrmMain_Laborant extends javax.swing.JFrame {

    Laborant laborant;
    List<Rezultat> rezultati = new ArrayList<>();
    List<Analiza> analize = new ArrayList<>();
    TableModelAnalize tblModelAnalize;
    Uput uput;
    Analiza analiza;
    Rezultat rezultat;

    /**
     * Creates new form FrmMain_Laborant
     */
    public FrmMain_Laborant(Laborant laborant) {
        initComponents();
        this.laborant = laborant;
        ClientController.getInstance().setFrmLaborant(this);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalizeRez = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSifraUputa = new javax.swing.JTextField();
        txtDatumUputa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLekar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRezultat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnZapamti = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtVrstaUzorka = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAnaliza = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLaborant = new javax.swing.JTextField();
        lblLaborant = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MedicalIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 2, 14), new java.awt.Color(0, 153, 255))); // NOI18N

        tblAnalizeRez.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnalizeRez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnalizeRezMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnalizeRez);

        jLabel1.setText("Lista uputa");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaz uputa i unos rezultata"));

        jLabel2.setText("Broj protokola");

        txtSifraUputa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSifraUputa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSifraUputa.setEnabled(false);
        txtSifraUputa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraUputaActionPerformed(evt);
            }
        });

        txtDatumUputa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDatumUputa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDatumUputa.setEnabled(false);

        jLabel3.setText("Datum uputa");

        jLabel6.setText("Lekar");

        txtLekar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLekar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLekar.setEnabled(false);

        txtRezultat.setColumns(20);
        txtRezultat.setRows(5);
        jScrollPane2.setViewportView(txtRezultat);

        jLabel8.setText("Rezultat:");

        btnZapamti.setText("Zapamti");
        btnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapamtiActionPerformed(evt);
            }
        });

        jLabel10.setText("Vrsta uzorka");

        txtVrstaUzorka.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVrstaUzorka.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtVrstaUzorka.setEnabled(false);

        jLabel4.setText("Analiza");

        txtAnaliza.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAnaliza.setEnabled(false);

        jLabel5.setText("Laborant");

        txtLaborant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLaborant.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtLaborant.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(txtSifraUputa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatumUputa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtVrstaUzorka, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4))
                            .addComponent(txtAnaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLekar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtLaborant))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSifraUputa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumUputa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLekar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrstaUzorka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnaliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLaborant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(btnZapamti)
                .addGap(16, 16, 16))
        );

        lblLaborant.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLaborant)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLaborant)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapamtiActionPerformed
        if (uput != null && rezultat != null && !txtSifraUputa.getText().isEmpty() && !txtRezultat.getText().isEmpty()) {
            try {
                Rezultat rez = new Rezultat();
                rez.setBrojProtokola(uput.getSifraUputa());
                rez.setRezultat_analize(txtRezultat.getText());
                rez.setLaborant(laborant);
                rez.setDatumIzdavanja(new Date());

                ClientController.getInstance().insertRezultat(rez);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate odabrati uput i upisati vrednost rezultata!", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnZapamtiActionPerformed

    private void tblAnalizeRezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnalizeRezMouseClicked

        int row = tblAnalizeRez.rowAtPoint(evt.getPoint());

        Uput u = tblModelAnalize.getUput(row);
        Rezultat r = tblModelAnalize.getRezultat(row);

        uput = u;
        rezultat = r;

        txtAnaliza.setText(u.getAnaliza());
        txtSifraUputa.setText(u.getSifraUputa().toString());
        txtDatumUputa.setText(u.getDatumUputa().toString());
        txtVrstaUzorka.setText(u.getVrstaUzorka());
        txtLekar.setText(u.getLekar().getIme() + " " + u.getLekar().getPrezime());
        if (rezultat != null && rezultat.getRezultat_analize() != null) {
            txtRezultat.setText(r.getRezultat_analize());
            txtLaborant.setText(r.getLaborant().getIme() + " " + r.getLaborant().getPrezime());
        }

        //JOptionPane.showMessageDialog(this, tblModelUputi.getUputRezultat(row));

    }//GEN-LAST:event_tblAnalizeRezMouseClicked

    private void txtSifraUputaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraUputaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraUputaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZapamti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLaborant;
    private javax.swing.JTable tblAnalizeRez;
    private javax.swing.JTextField txtAnaliza;
    private javax.swing.JTextField txtDatumUputa;
    private javax.swing.JTextField txtLaborant;
    private javax.swing.JTextField txtLekar;
    private javax.swing.JTextArea txtRezultat;
    private javax.swing.JTextField txtSifraUputa;
    private javax.swing.JTextField txtVrstaUzorka;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        try {
            ClientController.getInstance().getAnalize();
            ClientController.getInstance().getRezultati();

            tblModelAnalize = new TableModelAnalize();
            tblAnalizeRez.setModel(tblModelAnalize);

            lblLaborant.setText(laborant.getIme() + " " + laborant.getPrezime() + "(" + laborant.getUsername() + ")");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska u preuzimanju podataka: " + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void setRezultati(Response response) {
        rezultati = (List<Rezultat>) response.getResponse();
        for (Rezultat r : rezultati) {
            System.out.println();
        }

        if (!analize.isEmpty()) {
            tblModelAnalize.setAnalizeRezultati(analize, rezultati);
        }
        //tblModelUputiRez.setRezultati(rezultati);
    }

    public void notifyInsert(String message) {
        JOptionPane.showMessageDialog(this, message);

        try {
            ClientController.getInstance().getRezultati();
            ClientController.getInstance().notifyOthers();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain_Laborant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void refresh() {
        prepareForm();
    }

    public void showAnalize(Response response) {
        if (response.getResponseType().equals(ResponseType.SUCCESS)) {
            analize = (List<Analiza>) response.getResponse();
            tblModelAnalize.setAnalize(analize);
        }
    }
}
